### ISSUE TITLE
deploy to heroku

### ISSUE THREAD

**Issue by shop2world** [ayushkumarshah/Guitar-Chords-recognition#7]
Hello. It's a very good program.
It's really interesting.
But is it possible deploy it to heroku?
When I try it, I have the following problem.

https://imgur.com/2fgJcCu

remote:        ERROR: Could not find a version that satisfies the requirement mkl-service (from -r /tmp/build_cd95f861/requirements.txt (line 55)) (from versions: none)
remote:        ERROR: No matching distribution found for mkl-service (from -r /tmp/build_cd95f861/requirements.txt (line 55))
remote:  !     Push rejected, failed to compile Python app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to shop2harmoney.
remote:
To https://git.heroku.com/shop2harmoney.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/shop2harmoney.git'

thank you!

**Comment by ayushkumarshah** [comment]
Thank you for the compliment. Currently, it is not guaranteed to work after deployment since the application needs to record sound from the user's microphone and the audio device needs to be set (varies according to the user's device). This feature is currently not supported by `streamlit` and I haven't found any solution or other workaround yet. So, it is not worth deploying now until the recording problem is figured out.

**Comment by shop2world** [comment]
Thanks for the kind answer. 
The problem is clear, so I will ask streamlit for an upgrade to that feature.
Regards.
